-- RBAC management catalogue (roles + permissions surfaced by /api/v1/{roles,permissions}).
-- Seeded on first run by the app when the tables are empty.

CREATE TABLE IF NOT EXISTS permissions (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT        NOT NULL UNIQUE,
    guard_name  TEXT        NOT NULL DEFAULT 'api',
    description TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS roles (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           TEXT        NOT NULL UNIQUE,
    guard_name     TEXT        NOT NULL DEFAULT 'api',
    description    TEXT,
    permission_ids INT[]       NOT NULL DEFAULT '{}',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
